version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"  # Spring Boot app port
    environment: 
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/eucl
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwerty123
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: eucl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
    ports:
      - "5432:5432"
    volumes:
      - eucl-db-data:/var/lib/postgresql/data

volumes:
  eucl-db-data: